### ISSUE TITLE
What is your results on fddb or other face detection datasets?

### ISSUE THREAD

**Issue by IssacCyj** [imistyrain/ssd-face#1]
What is your results on fddb or other face detection datasets?

**Comment by imistyrain** [comment]
Sorry for late response. I'm too busy to test it on fddb. If any one have tested it, please give me a result.

**Comment by curry8** [comment]
I just test it in my own video, it had a high false detection rate.

**Comment by jiangfan2** [comment]
权重百度云盘文件已失效，麻烦再给一个

**Comment by imistyrain** [comment]
已经在[releases](https://github.com/imistyrain/ssd-face/releases)里提供权重文件
